language: node_js 
before_script: 
- "npm install -g se-interpreter" 
script: 
- "se-interpreter test.json" 
env: 
  matrix: 
  - SAUCE_PLATFORM='Windows 7' SAUCE_BROWSER='googlechrome' SAUCE_BROWSER_VERSION='37'